### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by useragent23253** [StarfireLab/SharpWeb#1]
Hello, what about Microsoft Edge?

**Comment by lele8** [comment]
?

**Comment by lele8** [comment]
?

**Comment by lele8** [comment]
What happened to Microsoft Edge?

**Comment by useragent23253** [comment]
This soft did not dump data from Edge browser. I'm using it like this sharpweb.exe -all -all
I got data only from firefox and chromium

**Comment by lele8** [comment]
你的edge是默认安装的路径吗

**Comment by useragent23253** [comment]
Yep, my bad. Working.

**Comment by lele8** [comment]
你可以试试sharpweb.exe -b chromium -p "C:\Users\test\AppData\Local\Microsoft\Edge\User Data\Default"，这样能不能解。我暂时没碰到过你说的问题
